CREATE TABLE IF NOT EXISTS users (
  uid INT NOT NULL AUTO_INCREMENT,
  userName VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  isNew BOOLEAN NOT NULL DEFAULT true,
  currency VARCHAR(10) DEFAULT NULL,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  isCustomer TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (uid),
  UNIQUE KEY email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;