CREATE TABLE IF NOT EXISTS orders (
  id INT NOT NULL AUTO_INCREMENT,
  orderNumber INT NOT NULL  DEFAULT 0,
  businessId INT NOT NULL,
  customerId VARCHAR(255) NOT NULL,
  paymentIntentId VARCHAR(255) DEFAULT NULL,
  data JSON NOT NULL,
  type VARCHAR(50) NOT NULL DEFAULT "unknown",
  status VARCHAR(50) NOT NULL,
  pickupAt  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      ON UPDATE CURRENT_TIMESTAMP,
  totalPrice DECIMAL(10,2) DEFAULT NULL,
  currency VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_businessId (businessId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;