CREATE TABLE IF NOT EXISTS businessFeatures (
  id INT NOT NULL AUTO_INCREMENT,
  businessId INT NOT NULL,
  featureId INT NOT NULL,
  isEnabled TINYINT(1) NOT NULL DEFAULT 1,
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP 
      ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_businessId (businessId),
  KEY idx_featureId (featureId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;