CREATE TABLE IF NOT EXISTS productCategories ( 
    id INT AUTO_INCREMENT PRIMARY KEY,
    businessId INT NOT NULL, 
    value VARCHAR(255) NOT NULL,
    label VARCHAR(255) NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, 
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
);