CREATE TABLE IF NOT EXISTS menuBooks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid INT NOT NULL,
  isPublic TINYINT(1) NOT NULL DEFAULT 0,
  publicCode VARCHAR(255) DEFAULT NULL,
  price INT NOT NULL DEFAULT 1,
  information JSON DEFAULT NULL,
  category VARCHAR(255) DEFAULT NULL,
  type VARCHAR(255) NOT NULL DEFAULT 'demo',
  heading VARCHAR(255) DEFAULT NULL,
  subheading VARCHAR(255) DEFAULT NULL,
  templateCode VARCHAR(255) DEFAULT NULL,
  menuBookCode VARCHAR(255) NOT NULL,
  contents JSON DEFAULT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_uid (uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;