CREATE TABLE IF NOT EXISTS sockets (
  id INT NOT NULL AUTO_INCREMENT,
  uid INT NOT NULL,
  socketID VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
      ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_uid (uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;