CREATE TABLE IF NOT EXISTS kitchenCapacity (
  id INT PRIMARY KEY AUTO_INCREMENT,
  businessId INT NOT NULL UNIQUE,

  maxOrdersPerSlot INT NOT NULL DEFAULT 5,
  slotMinutes INT NOT NULL DEFAULT 15,
  prepMinutes INT NOT NULL DEFAULT 15,
  slotLimit INT NOT NULL DEFAULT 5,

  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);