CREATE TABLE IF NOT EXISTS payments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid BIGINT NOT NULL,
  paymentIntentId VARCHAR(255) NOT NULL,
  customerId VARCHAR(255) DEFAULT NULL,
  clientSecret VARCHAR(500) NOT NULL,
  status VARCHAR(50) NOT NULL,
  type VARCHAR(255) NOT NULL,
  amount DECIMAL(10, 2) DEFAULT 0.00,
  changeAmount DECIMAL(10, 2) DEFAULT 0.00,
  currency CHAR(3) DEFAULT NULL,
  createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
      ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_uid (uid),
  KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;