CREATE TABLE IF NOT EXISTS tableOrders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tableId INT NOT NULL,
    data JSON NOT NULL,
    totalPrice INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    orders JSON DEFAULT NULL,
    currency VARCHAR(10) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_table_orders_table
        FOREIGN KEY (tableId)
        REFERENCES tables(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);