CREATE TABLE IF NOT EXISTS templates (
  id BIGINT NOT NULL AUTO_INCREMENT,
  uid INT NOT NULL,
  code VARCHAR(100) NOT NULL,
  publicCode VARCHAR(100) DEFAULT NULL,
  isPublic TINYINT(1) NOT NULL DEFAULT 0,
  category VARCHAR(100) NOT NULL,
  type VARCHAR(100) NOT NULL,
  heading VARCHAR(255) DEFAULT NULL,
  subheading VARCHAR(255) DEFAULT NULL,
  information JSON DEFAULT NULL,
  contents JSON NOT NULL,
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  price INT DEFAULT 1,
  extras JSON DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_uid (uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;