CREATE TABLE IF NOT EXISTS subscriptions (
  id INT NOT NULL AUTO_INCREMENT,
  businessID INT NOT NULL,
  subscriptionId INT NOT NULL,
  startDate DATETIME NOT NULL,
  endDate DATETIME DEFAULT NULL,
  isActive TINYINT(1) NOT NULL DEFAULT 1,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      ON UPDATE CURRENT_TIMESTAMP,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_businessID (businessID),
  KEY idx_subscriptionId (subscriptionId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;