CREATE TABLE IF NOT EXISTS businessStripeAccounts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  businessId BIGINT UNSIGNED NOT NULL,
  stripeAccountId VARCHAR(255) NOT NULL,
  locationId VARCHAR(255) DEFAULT NULL,
  payoutsEnabled BOOLEAN NOT NULL DEFAULT FALSE,
  chargesEnabled BOOLEAN NOT NULL DEFAULT FALSE,
  detailsSubmitted BOOLEAN NOT NULL DEFAULT FALSE,
  applyPay BOOLEAN NOT NULL DEFAULT FALSE
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_stripe_account (stripeAccountId),
  UNIQUE KEY uniq_business (businessId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;