CREATE TABLE IF NOT EXISTS pricing (
  id INT NOT NULL AUTO_INCREMENT,
  type VARCHAR(255) DEFAULT NULL,
  pack VARCHAR(100) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  currency VARCHAR(10) NOT NULL,
  tokens INT NOT NULL,
  description TEXT DEFAULT NULL,
  items JSON DEFAULT NULL,
  highlighted TINYINT(1) NOT NULL DEFAULT 0,
  popular TINYINT(1) NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY unique_pack (pack)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;