CREATE TABLE IF NOT EXISTS businesses (
  id INT NOT NULL AUTO_INCREMENT,
  uid INT NOT NULL,
  internalId VARCHAR(255) DEFAULT NULL UNIQUE,
  passCode VARCHAR(255) NOT NULL,
  name VARCHAR(255) DEFAULT NULL,
  description TEXT,
  address VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  website VARCHAR(255) DEFAULT NULL,
  openHours JSON DEFAULT NULL,
  logo LONGTEXT DEFAULT NULL,
  theme VARCHAR(255) ENUM('light', 'dark') DEFAULT NULL DEFAULT "light",
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
      ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY unique_uid (uid),
  UNIQUE KEY unique_internalId (internalId),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


