services:
  node-app:
    image: minhlu14206/order-service:latest
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${SOCKET_PORT}:${SOCKET_PORT}"
    env_file:
      - .env