name: Deploy order-service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Instance-1
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST_INSTANCE_1 }}
          username: ${{ secrets.SERVER_USER_INSTANCE_1 }}
          key: ${{ secrets.SERVER_SSH_KEY_INSTANCE_1 }}
          script: |
            /root/deploy/order-deploy.ssh

      - name: Deploy to Instance-2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST_INSTANCE_2 }}
          username: ${{ secrets.SERVER_USER_INSTANCE_2 }}
          key: ${{ secrets.SERVER_SSH_KEY_INSTANCE_2 }}
          script: |
            /root/deploy/order-deploy.ssh